#!/usr/bin/env python3
"""Aggregate run outputs into the Table-1-style summary.

Reads <root>/results/runs/<model>_<task>_<mode>_<pos>_seed<k>/ (written by
scripts/run_one.sh) and writes logs/summary.json + logs/summary.md in the repo.
Accuracies are percentages. Generated tokens are counted by re-tokenizing the
decoded test responses with the run's tokenizer (special tokens were stripped
by upstream decoding, so this slightly undercounts the trailing <|im_end|>).
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import re
import statistics

RUN_RE = re.compile(r"^(?P<model>qwen3_8b|qwen35_4b)_(?P<task>searchqa|livemath)_(?P<mode>train|init|noskill|hard)_(?P<pos>prompt_start|skill_section)_seed(?P<seed>\d+)$")
TEST_KEYS = {  # mode -> (summary key prefix, results.jsonl relative path)
    "train": ("test", "eval/best/valid_unseen/results.jsonl"),
    "init": ("init_test", "eval/init/valid_unseen/results.jsonl"),
    "noskill": ("plain_test", "eval/plain/valid_unseen/results.jsonl"),
    "hard": ("plain_test", "eval/plain/valid_unseen/results.jsonl"),
}
VAL_KEYS = {"init": "init_valid_seen", "noskill": "plain_valid_seen", "hard": "plain_valid_seen"}
MODEL_PATHS = {"qwen3_8b": "/data/models/huggingface/qwen3-8b", "qwen35_4b": "/data/models/library/Qwen3.5-4B"}
MAX_NEW = {"searchqa": 64, "livemath": 16}


def load_jsonl(path: str) -> list[dict]:
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def fmt(values: list[float]) -> str:
    if not values:
        return "–"
    if len(values) == 1:
        return f"{values[0]:.1f}"
    return f"{statistics.mean(values):.1f} ± {statistics.stdev(values):.1f}"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="/data/a84460786/softskill_qwen3")
    ap.add_argument("--out_dir", default=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "logs"))
    args = ap.parse_args()

    from transformers import AutoTokenizer

    tokenizers: dict[str, object] = {}
    runs = []
    for run_dir in sorted(glob.glob(os.path.join(args.root, "results", "runs", "*"))):
        m = RUN_RE.match(os.path.basename(run_dir))
        summary_path = os.path.join(run_dir, "summary.json")
        if not m or not os.path.exists(summary_path):
            continue
        info = m.groupdict()
        info["seed"] = int(info["seed"])
        with open(summary_path, encoding="utf-8") as f:
            summary = json.load(f)
        prefix, rel = TEST_KEYS[info["mode"]]
        rec = dict(info, run=os.path.basename(run_dir))
        rec["test_hard"] = 100 * summary[f"{prefix}_hard"] if summary.get(f"{prefix}_hard") is not None else None
        rec["test_soft"] = 100 * summary[f"{prefix}_soft"] if summary.get(f"{prefix}_soft") is not None else None
        if info["mode"] == "train":
            hist = summary.get("history") or []
            accepted = [h for h in hist if h.get("action") == "accept_new_best"]
            rec["selected_epoch"] = accepted[-1]["epoch"] if accepted else None
            rec["history"] = [
                {k: h.get(k) for k in ("epoch", "loss", "valid_seen_hard", "valid_seen_soft", "gate_metric", "action", "wall_time_s")}
                for h in hist
            ]
        else:
            key = VAL_KEYS[info["mode"]]
            rec["val_hard"] = 100 * summary[f"{key}_hard"] if summary.get(f"{key}_hard") is not None else None
        rows = load_jsonl(os.path.join(run_dir, rel))
        rec["n_test"] = len(rows)
        if rows:
            tok = tokenizers.setdefault(info["model"], AutoTokenizer.from_pretrained(MODEL_PATHS[info["model"]]))
            lens = [len(tok(str(r.get("response", "")), add_special_tokens=False)["input_ids"]) for r in rows]
            rec["avg_gen_tokens"] = statistics.mean(lens)
            rec["frac_hit_max_new_tokens"] = sum(n >= MAX_NEW[info["task"]] for n in lens) / len(lens)
        runs.append(rec)

    os.makedirs(args.out_dir, exist_ok=True)
    with open(os.path.join(args.out_dir, "summary.json"), "w", encoding="utf-8") as f:
        json.dump(runs, f, indent=2)

    lines = ["# Run summary (auto-generated by scripts/summarize.py)", ""]
    methods = [
        ("No skill", "noskill", None),
        ("Hard skill (SkillOpt artifact, text)", "hard", None),
        ("Init-only p0, prompt_start", "init", "prompt_start"),
        ("Init-only p0, skill_section", "init", "skill_section"),
        ("SoftSkill, prompt_start", "train", "prompt_start"),
        ("SoftSkill, skill_section", "train", "skill_section"),
    ]
    for model in sorted({r["model"] for r in runs}):
        lines += [f"## {model}", "", "| Method | SearchQA test-hard | SearchQA test-soft | LiveMath test-hard | LiveMath test-soft | seeds (SQA/LM) |", "|---|---|---|---|---|---|"]
        for label, mode, pos in methods:
            cells, seeds = [], []
            for task in ("searchqa", "livemath"):
                sel = [r for r in runs if r["model"] == model and r["task"] == task and r["mode"] == mode and (pos is None or r["pos"] == pos)]
                cells += [fmt([r["test_hard"] for r in sel if r["test_hard"] is not None]), fmt([r["test_soft"] for r in sel if r["test_soft"] is not None])]
                seeds.append(",".join(str(r["seed"]) for r in sorted(sel, key=lambda r: r["seed"])) or "–")
            lines.append(f"| {label} | " + " | ".join(cells) + f" | {' / '.join(seeds)} |")
        lines += ["", "### Per-run", "", "| Run | test-hard | test-soft | selected epoch | val (per epoch, gate metric) | avg gen tokens | hit max_new_tokens |", "|---|---|---|---|---|---|---|"]
        for r in [r for r in runs if r["model"] == model]:
            val = ""
            if r["mode"] == "train":
                val = "; ".join(
                    f"e{h['epoch']}: hard {100 * h['valid_seen_hard']:.1f} / soft {100 * h['valid_seen_soft']:.1f}" for h in r["history"]
                ) + f" (gate={r['history'][0]['gate_metric'] if r['history'] else '?'})"
            elif r.get("val_hard") is not None:
                val = f"hard {r['val_hard']:.1f}"
            th = f"{r['test_hard']:.1f}" if r["test_hard"] is not None else "–"
            ts = f"{r['test_soft']:.1f}" if r["test_soft"] is not None else "–"
            agt = f"{r['avg_gen_tokens']:.1f}" if r.get("avg_gen_tokens") is not None else "–"
            hit = f"{100 * r['frac_hit_max_new_tokens']:.0f}%" if r.get("frac_hit_max_new_tokens") is not None else "–"
            lines.append(f"| {r['run']} | {th} | {ts} | {r.get('selected_epoch', '') or ''} | {val} | {agt} | {hit} |")
        lines.append("")
    with open(os.path.join(args.out_dir, "summary.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
